### ISSUE TITLE
[BUG] - Datatable

### ISSUE THREAD

**Issue by caio-cares** [TiendaNube/nimbus-patterns#29]
🐛 **Describe the bug**
Quando clica no checkbox dentro do DataTable.Row não seleciona o item, se você clica ao lado no texto seleciona.

🧐 **To Reproduce**

1. Clique no checkbox da lista - ele não irá marcar
2. Clique no texto ao lado ex: pedido 27 - ele irá marcar

📷 **Screenshots**
![image](https://user-images.githubusercontent.com/50033091/228065271-6e748f3a-b305-4c6c-b6a7-dbd0f306e3a1.png)

Encontrei aqui
https://nimbus.nuvemshop.com.br/documentation/patterns/data-table

https://user-images.githubusercontent.com/29050634/228066570-d815458b-73ec-4a46-9a7d-39dec5ea26b0.mov

**Comment by juanchigallego** [comment]
Bom dia @caio-cares , obrigado por reportar o issue!
O bug acontece porque o evento onclick esta aplicado sobre o elemento da row e não sobre o checkbox, porém tem um conflito de sobreposição dos eventos, mas o issue não é do componente se não da implementação do exemplo na historia. Vamos levar a tarefa de revisar a implementação para que o exemplo funcione corretamente.
