### ISSUE TITLE
[BUG] DataTable checkbox not displaying correctly when using box-sizing:border-box

### ISSUE THREAD

**Issue by juanchigallego** [TiendaNube/nimbus-patterns#42]
🐛 **Describe the bug**
Cuando se utiliza la propiedad de CSS `box-sizing: border-box` en algún ancestro del componente `DataTable`, el tamaño de la celda que tiene el checkbox se ve alterado. Para solucionar esto, es necesario aplicar `box-sizing: content-box`. Esto puede producir efectos indeseados en otros elementos de la pantalla.

Habitualmente se utiliza la propiedad `box-sizing: border-box` en un selector global `*`. En estos casos el componente va a verse de forma incorrecta siempre que lo utilicemos.

🧐 **To Reproduce**

1. Importar el componente DataTable
2. Colocar la propiedad `* { box-sizing: border-box; }` en el css de la aplicación
3. Verificar que los checkboxes de las celdas se rompen
4. Cambiar el valor de `box-sizing` a `content-box`
5. Confirmar que ahora se ve correctamente

✅ **Expected behavior**
El tamaño de la celda debiera verse correctamente sin importar las propiedades que coloquemos en otros elementos del DOM.

📷 **Screenshots**
| Cómo se debería ver  | Cómo se ve |
|--------|--------|
| <img width="600" alt="Captura de pantalla 2023-04-12 a la(s) 13 07 45" src="https://user-images.githubusercontent.com/25963096/231518138-9c0cf25b-47d9-4acd-b99c-bc8be9ebf314.png"> | <img width="600" alt="Captura de pantalla 2023-04-12 a la(s) 13 09 31" src="https://user-images.githubusercontent.com/25963096/231518148-516ea5a6-dba9-4715-a2bc-4621a059a435.png"> |

**Comment by juniorconquista** [comment]
Resolvido!
