### ISSUE TITLE
[BUG] SideModal footer actions does not accept "onClick"

### ISSUE THREAD

**Issue by guidobotta** [TiendaNube/nimbus-patterns#67]
🐛 **Describe the bug**

SideModal has a prop which is `footer`, each action is a `ButtonProperties`.

*(packages/react/src/components/SideModal/src/sideModal.types.ts)*
```tsx
export interface SideModalProperties
  extends Pick<
    SidebarProperties,
    "position" | "onRemove" | "open" | "padding" | "maxWidth" | "zIndex"
  > {
 ...
  /**
   * Footer element actions.
   */
  footer?: {
    primaryAction: ButtonProperties;
    secondaryAction: ButtonProperties;
  };
}
```

The problem is `ButtonProperties` only accepts `children`, `appearance` and `disabled`:

*(packages/react/src/atomic/Button/src/button.types.ts)*
```tsx
export interface ButtonProperties {
  /**
   * The content of the button.
   * @TJS-type React.ReactNode
   */
  children: ReactNode;
  /**
   * Change the visual style of the button.
   * @default neutral
   */
  appearance?: "primary" | "danger" | "neutral" | "transparent";
  /**
   * Disables the button, disallowing user interaction.
   * @default false
   */
  disabled?: boolean;
}
```

So it is not possible to set an `onClick` prop to the footer buttons. There's also no other way those click actions could be set as the footer buttons are created as following:

*(packages/react/src/components/SideModal/src/SideModal.tsx)*
```tsx
{!!footer && (
  <Sidebar.Footer padding={paddingFooter || "base"}>
    <Button {...footer.primaryAction} />
    <Button {...footer.secondaryAction} />
  </Sidebar.Footer>
)}
```

I think the correct type to be set to `primaryAction` and `secondaryAction` is `ButtonBaseProps`:

*(packages/react/src/atomic/Button/src/button.types.ts)*
```tsx
export type ButtonBaseProps = ButtonProperties &
  ButtonHTMLAttributes<HTMLButtonElement>;
```

✅ **Expected behavior**

I wish I could set the `onClick` prop to the `footer` actions.

**Comment by juniorconquista** [comment]
@guidobotta muito obrigado por reportar esse bug, ele foi resolvido na PR https://github.com/TiendaNube/nimbus-patterns/pull/69.

Para pegar essa correção basta fazer os updates do pacote do nimbus.
